services:
  rozzet_gallery_postgres_1:
    container_name: rozzet_gallery_postgres_1
    image: postgres:16.4
    volumes:
      - rozzet_gallery_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - rozzet_gallery_network

  rozzet_gallery_app_1:
    container_name: rozzet_gallery_app_1
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - APP_PORT=8000
      - APP_HOST=0.0.0.0
      - TZ=UTC
      - DATABASE_CONNECTION=postgres
      - DATABASE_HOST=rozzet_gallery_postgres_1
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    depends_on:
      - rozzet_gallery_postgres_1
    networks:
      - rozzet_gallery_network

volumes:
  rozzet_gallery_postgres_data:
    driver: local
    name: rozzet_gallery_postgres_data

networks:
  rozzet_gallery_network:
    driver: bridge
    name: rozzet_gallery_network
